import qulacs_osaka_core

def bravyi_kitaev(fermion_operator: qulacs_osaka_core.FermionOperator, n_qubits: int) -> qulacs_osaka_core.Observable: ...
def jordan_wigner(fermion_operator: qulacs_osaka_core.FermionOperator) -> qulacs_osaka_core.Observable: ...
