version: 2

sphinx:
  configuration: doc/ja/source/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  apt_packages:
    - cmake
    - libboost-dev

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
